# Dependabot configuration for SecPal
version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "dependabot"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    target-branch: "main"
    allow:
      - dependency-type: "all"
    insecure-external-code-execution: "deny"
    pull-request-branch-name:
      separator: "-"
