# SPDX-FileCopyrightText: 2025 SecPal
# SPDX-License-Identifier: CC0-1.0

# This workflow enforces CLA signatures for all pull requests
# It uses a centralized reusable workflow from SecPal/.github
#
# Setup required:
# 1. Add CLA_BOT_TOKEN as an organization secret (Settings → Secrets → Actions)
#    OR add it as a repository secret in each repo
# 2. The token must be a Personal Access Token with 'repo' scope
#
# All CLA signatures are stored centrally in SecPal/.github (branch: cla-signatures)

name: CLA Assistant

on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  cla:
    name: Check CLA
    uses: SecPal/.github/.github/workflows/cla-reusable.yml@main
    secrets:
      CLA_BOT_TOKEN: ${{ secrets.CLA_BOT_TOKEN }}
