# SPDX-FileCopyrightText: 2025 SecPal
# SPDX-License-Identifier: CC0-1.0

name: CLA Assistant

on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  cla:
    name: CLA Assistant
    runs-on: ubuntu-latest
    steps:
      - name: Validate CLA_BOT_TOKEN
        run: |
          if [ -z "${{ secrets.CLA_BOT_TOKEN }}" ]; then
            echo "::error::CLA_BOT_TOKEN secret is not configured. Please add it in Repository Settings → Secrets."
            echo "::error::The secret requires a Personal Access Token with 'repo' scope."
            exit 1
          fi

      - name: CLA Assistant
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CLA_BOT_TOKEN: Personal Access Token (PAT) with 'repo' scope
          # Required to commit signatures to the cla-signatures branch
          # Setup: Repository Settings → Secrets → New repository secret
          # Name: CLA_BOT_TOKEN | Value: Your PAT
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_BOT_TOKEN }}
        with:
          # Path to CLA document
          path-to-document: "https://github.com/SecPal/.github/blob/main/CLA.md"
          # Branch to store CLA signatures
          branch: "cla-signatures"
          # Allowlist: Bots and automated accounts
          allowlist: bot*,dependabot*,renovate*,github-actions*
          # Remote organization name (if CLA is stored in a different repo)
          remote-organization-name: "SecPal"
          remote-repository-name: ".github"
          # Create file commit message
          create-file-commit-message: "chore: create CLA signatures file"
          # Signed commit message
          signed-commit-message: "chore: $contributorName has signed the CLA"
          # Custom PR comment for unsigned contributors
          custom-pr-sign-comment: |
            Thank you for your contribution! 🎉

            Before we can merge this pull request, we need you to sign our **Contributor License Agreement (CLA)**.

            ## Why do we need a CLA?

            SecPal uses a dual-licensing model:
            - **Open Source**: All contributions are licensed under AGPL-3.0-or-later
            - **Commercial**: We may offer commercial licenses to customers

            The CLA ensures we have the necessary rights for both licensing models while you retain copyright ownership.

            ## How to Sign

            **Option 1: Automated Signing (Recommended)**
            1. Read our [CLA Document](https://github.com/SecPal/.github/blob/main/CLA.md)
            2. Comment on this PR with:
               ```
               I have read the CLA Document and I hereby sign the CLA
               ```

            **Option 2: Manual Signing**
            - Individual contributors: Email signed CLA to [legal@secpal.app](mailto:legal@secpal.app)
            - Corporate contributors: Have authorized representative email signed Corporate CLA

            ## Already Signed?

            If you've already signed the CLA and this check is failing, comment:
            ```
            recheck
            ```

            ---

            Questions? Contact us at [legal@secpal.app](mailto:legal@secpal.app)
          # Custom PR comment for contributors who have signed
          custom-allsigned-prcomment: |
            All contributors have signed the CLA ✅

            Thank you for helping us maintain SecPal's dual-licensing model!
          # Lock PR after CLA is signed to prevent changes
          lock-pullrequest-aftermerge: false
