# SPDX-FileCopyrightText: 2025 SecPal
# SPDX-License-Identifier: AGPL-3.0-or-later

name: License Compatibility

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  license-check:
    uses: SecPal/.github/.github/workflows/reusable-license-compatibility.yml@main
