# SPDX-FileCopyrightText: 2025 SecPal
# SPDX-License-Identifier: CC0-1.0

# Project Board Automation for .github repository
# This workflow handles direct events (issues, PRs, reviews) in the .github repo
# and calls the core reusable workflow for the actual automation logic.
#
# For the core automation logic, see: project-automation-core.yml

name: Project Board Automation

on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request:
    types:
      - opened
      - ready_for_review
      - closed
      - converted_to_draft
  pull_request_review:
    types:
      - submitted

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  project-automation:
    name: Project automation
    uses: ./.github/workflows/project-automation-core.yml
    secrets:
      PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
