# SPDX-FileCopyrightText: 2025 SecPal
# SPDX-License-Identifier: AGPL-3.0-or-later

# Note: This workflow uses inline jobs instead of calling reusable workflows
# to avoid a chicken-and-egg problem: the reusable workflows are not yet
# available on the main branch until this PR is merged.
# Other repositories should use the reusable workflows via:
#   uses: SecPal/.github/.github/workflows/reusable-prettier.yml@main
#   uses: SecPal/.github/.github/workflows/reusable-markdown-lint.yml@main

name: Code Quality

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  reuse:
    name: Check REUSE Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5

  license-compatibility:
    name: Check License Compatibility
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install licensecheck
        run: pip install licensecheck

      - name: Run License Compatibility Check
        run: licensecheck

  prettier:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22.x"

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Prettier Check
        run: prettier --check '**/*.{md,yml,yaml,json}'

  markdown-lint:
    name: Lint Markdown Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: "**/*.md"
          config: ".markdownlint.json"
