# SPDX-FileCopyrightText: 2025 SecPal
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Reusable - Node.js Build

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        type: string
        default: "22.x"
      install-command:
        description: "Command to install dependencies"
        required: false
        type: string
        default: "npm ci"
      build-command:
        description: "Command to build the project"
        required: false
        type: string
        default: "npm run build"

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"

      - name: Install dependencies
        env:
          INSTALL_CMD: ${{ inputs.install-command }}
        run: $INSTALL_CMD

      - name: Build project
        env:
          BUILD_CMD: ${{ inputs.build-command }}
        run: $BUILD_CMD
