# SPDX-FileCopyrightText: 2025 SecPal
# SPDX-License-Identifier: AGPL-3.0-or-later

name: REUSE Compliance

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  reuse:
    uses: SecPal/.github/.github/workflows/reusable-reuse.yml@main
