# SPDX-FileCopyrightText: 2025 SecPal
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Reusable - Laravel Pint

on:
  workflow_call:
    inputs:
      php-version:
        description: "PHP version to use"
        required: false
        type: string
        default: "8.4"
      pint-command:
        description: "Command to run Laravel Pint"
        required: false
        type: string
        default: "./vendor/bin/pint --test"

jobs:
  pint:
    name: Check Code Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run Laravel Pint
        env:
          PINT_CMD: ${{ inputs.pint-command }}
        run: $PINT_CMD
