---
# SPDX-FileCopyrightText: 2025-2026 SecPal
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Reusable - actionlint

on:
  workflow_call:

permissions:
  checks: write
  contents: read

jobs:
  actionlint:
    name: Lint GitHub Actions Workflows
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run actionlint
        uses: reviewdog/action-actionlint@dbe5299849118fd6f099ba563d263d770955a64a # v1.73.2
        with:
          actionlint_flags: ""
