# SPDX-FileCopyrightText: 2025 SecPal
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Reusable - Node.js Tests

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        type: string
        default: "22.x"
      install-command:
        description: "Command to install dependencies"
        required: false
        type: string
        default: "npm ci"
      test-command:
        description: "Command to run tests"
        required: false
        type: string
        default: "npm test"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: ${{ inputs.install-command }}

      - name: Run tests
        run: ${{ inputs.test-command }}
